
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
      - "9009:9009"  # Interserver replication
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=default
    volumes:
      - ./db/schema/clickhouse.sql:/docker-entrypoint-initdb.d/init.sql:ro    
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      retries: 1
      start_period: 30s
      timeout: 10s

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: user_management      
    volumes:
      - ./db/schema/mysql.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CLICKHOUSE_HOST=clickhouse
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root1234
      - DB_NAME=user_management
    depends_on:
      clickhouse:
        condition: service_healthy
      mysql:
        condition: service_healthy


    

